# Generated by Django 4.0.4 on 2022-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description_product_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
